### ISSUE TITLE
Green or black screen

### ISSUE THREAD

**Issue by EwannAnacombesque** [lmarz/asm_gl#1]
File **runs**, however it randomly shows full **green** screen, or full **black** screen, at an equal probability (as far as i know), when i restart the program.
The issue persists even if the code is reduced to its minimal form (no triangle drawn, just the screen by glClear, swapping buffers etc). If the glClearColor part is skipped, there is no green, the screen is always black, which makes sens. However, when i take out of the main loop the glClear part, it alternates quickly green and black, or it only shows black. 
Rarely, the green displayed isn't the pure green (255), but a slightly darker (225) or a much darker (112).  These strange values make me think the issue could be obvious, cause those are oddly on "round" numbers. Maybe does it come from buffer swapping cause even without refreshing the screen, there are flashing. 
Furthermore, if you have any ressource that could help me about glfw and openGL in assembly, i'ld glad.
![Capture d'écran 2023-10-31 001532](https://github.com/lmarz/asm_gl/assets/67865912/03acfbbe-979b-4edb-8242-3d1f10883623)
Thanks

**Comment by lmarz** [comment]
If you want to call a c function from a library, like OpenGL, in assembly, you just have to follow the calling convention. The osdev wiki has a good reference to it: https://wiki.osdev.org/Calling_Conventions

So basically, if you want to call a function from the library libfoo which looks like this:
```c
int bar(int arg1, char *arg2, void *arg3);
```
If you are on an amd64 (x86_64) machine with linux, you first write in the assembly that there is an external function called "bar".
```asm
extern bar
```
And when you want to call it you simply type
```asm
call bar
```
Now there are also arguments to this function, which we have to set first. To to this, we set specific registers to the arguments and the function can just take them from there. Which register matches which argument position is defined in the
[System V Application Binary Interface AMD64 Architecture Processor Supplement](https://gitlab.com/x86-psABIs/x86-64-ABI/-/jobs/artifacts/master/raw/x86-64-ABI/abi.pdf?job=build) Section 3.2.3, where Figure 3.5 and 3.6 give a good example. So the first argument in our case goes in `%rdi`, the second goes into `%rsi` and the third goes into `%rdx`
```asm
mov rdi, 5              ;arg1
mov rsi, text           ;arg2 text is defined in a data section
lea rdx, [rel callback] ;arg3 callback is a function you defined
call bar
```
Note that when there's a floating point type like float or double, there are separate registers. Which is probably why my code desn't really work.
Also there are some registers which the function may override. See the documents for more detail.
After the function returns, the resulting int should be in `%rax`.
The last step would be to link the library, so you just have to add -lfoo to the ld call. Then it should work.
```sh
ld -o <executable> <object files> --dynamic-linker=/lib64/ld-linux-x86-64.so.2 -lfoo
```


Regarding the bugs you reported, I'll try to rewrite the code to work as expected when I find the time and motivation for it. This is a toy project after all :)
