### ISSUE TITLE
Purple screen

### ISSUE THREAD

**Issue by Quark-Hell** [lmarz/asm_gl#2]
Hello. As I understood, this code should output the red triangle. But I get only purple screen.

I running code with: 
- Manjaro Linux x86_64
- KWin (X11)
- AMD Ryzen 5 2600 (12) @ 3.40 GHz
- NVIDIA Geforce RTX 3050

**Comment by lmarz** [comment]
Should be fixed with 873406317dd0194b50a7ed0b50c51d6f798fee26

**Comment by Quark-Hell** [comment]
![image](https://github.com/user-attachments/assets/e50db99b-e484-437c-86a8-d02594c8b329)
It's work, nice!
